### ISSUE TITLE
Extract cli part to github-reserved-names-cli?

### ISSUE THREAD

**Issue by fregante** [Mottie/github-reserved-names#15]
It doesn't seem very useful and it depends on `meow`, which is unnecessary for what's essentially a list of strings. Could it be extracted into its own package?

**Comment by Mottie** [comment]
Hi @fregante!

If you think it isn't useful, I could just completely remove it. I thought it might be useful when I first created it, but I haven't used it either.

**Comment by fregante** [comment]
Sounds good!

**Comment by Mottie** [comment]
Done in https://github.com/Mottie/github-reserved-names/commit/37b034d15ab341cbff9470dbfa9d6034690b816a
